<?php

namespace Api\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchesRepository extends EntityRepository
{
	public function byEvent($event)
	{
		$qb=$this ->createQueryBuilder('u')
			->select('u')
			->where('u.eventId = :event')
			->orderBy('u.id')
			->setParameter('event',$event);
		return $qb->getQuery() ->getResult();
	}


	public function byTeam($team)
	{
		$qb=$this ->createQueryBuilder('u')
			->select('u')
			->where('u.homeTeamId = :team')
			->orWhere('u.awayTeamId = :team')
			->orderBy('u.id')
			->setParameter('team',$team);
		return $qb->getQuery() ->getResult();
	}

}
